config/routes.rb
SocialThingamajig::Application.routes.draw do
  resources :users do
    resources :friend_circles
  end
  resources :posts
  get "feed" => "posts#feed", :as => "feed"
  resource :session, :only => [:new, :create, :destroy]
  resource :password, :except => [:edit]
  get 'password/edit/:pw_reset_token' => 'passwords#edit', :as => 'edit_password'
  
  root :to => "sessions#new"

end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  validates :user_id, :name, :presence  => true
  attr_accessible :user_id, :name, :friend_ids
  belongs_to :user
  has_many :friend_circle_memberships, :dependent => :destroy,
  :inverse_of => :friend_circle
  has_many :friends, :through => :friend_circle_memberships, :source => :user
  has_many :post_shares
  has_many :posts, :through => :post_shares
end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  validates :friend_circle, :user, :presence => true
  attr_accessible :friend_circle_id, :user_id

  belongs_to :friend_circle
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :post_id
  validates :title, :url, :post, :presence => true
  
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :user_id, :shared_circle_ids
  validates :title, :body, :user, :presence => true
  
  belongs_to :user
  has_many :links, :dependent => :destroy, :inverse_of => :post
  has_many :post_shares
  has_many :shared_circles, :through => :post_shares, :source => :friend_circle
  
  accepts_nested_attributes_for :links
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :post_id, :friend_circle_id
  validates :post, :friend_circle, :presence  => true
  
  belongs_to :post
  belongs_to :friend_circle
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :pw_reset_token
  attr_reader :password
  before_validation :generate_session_token, :on => :create
  validates :email, :session_token, :presence => true
  validates :email, :session_token, :uniqueness => true
  validates :password, :length => {:minimum  => 6, :allow_nil => true}

  has_many :friend_circle_memberships, :inverse_of => :user
  has_many :friend_circles, :inverse_of => :user
  has_many :friends, :through => :friend_circles, :source => :user
  has_many :posts
  

  def self.find_by_credentials(email, pw)
    @user = User.find_by_email(email)
    if @user && @user.is_password?(pw)
      @user
    end
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def generate_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    generate_session_token
    self.save!
  end

  def reset_pw_token!
    self.pw_reset_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.pw_reset_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    @user = User.find_by_id(params[:user_id])
    @friend_circle = FriendCircle.new
    :new
  end

  def create
    @friend_circle = FriendCircle.new(params[:friend_circle])
    if @friend_circle.save
      redirect_to user_url(@friend_circle.user)
    else
      flash.now[:errors] = @friend_circle.errors.full_messages
      render :new
    end
  end
  
  def edit
    @user = User.find_by_id(params[:user_id])
    @friend_circle = FriendCircle.find_by_id(params[:id])
    :edit
  end
  
  def update
    @friend_circle = FriendCircle.find_by_id(params[:id])
    if @friend_circle.update_attributes(params[:friend_circle])
      redirect_to user_friend_circle_url(@friend_circle.user, @friend_circle)
    else
      flash.now[:errors] = @friend_circle.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @friend_circle = FriendCircle.find_by_id(params[:id])
    @user = @friend_circle.user
    @friend_circle.destroy
    redirect_to user_url(@user)
  end
  
  def show
    @friend_circle = FriendCircle.find_by_id(params[:id])
    if current_user == @friend_circle.user
      :show
    else
      flash[:errors] = ["You can only view your own Circles"]
      redirect_to user_url(current_user)
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  def new
    :new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      UserMailer.reset_password_email(@user).deliver
      flash[:errors] = ["Check your email for instructions"]
      redirect_to new_session_url
    else
      flash.now[:errors] = ["Email Not Found"]
      render :new
    end
  end

  def edit
    @pw_reset_token = params[:pw_reset_token]
    :edit
  end

  def update
    @user = User.find_by_pw_reset_token(params[:pw_reset_token])
    if @user

      if @user.update_attributes(:password => params[:password])
        flash[:errors] = ["Password changed!"]
        redirect_to new_session_url
      else
        flash.now[:errors] = @user.errors.full_messages
        @pw_reset_token = params[:pw_reset_token]
        render :edit
      end
    else
      flash[:errors] = ["Link Expired"]
      redirect_to new_session_url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :ensure_logged_in
  
  def index
    @posts = current_user.posts
    :index
  end
  
  def new
    @post = Post.new
    3.times {@post.links.build}
    :new
  end
  
  def create
    @post = Post.new(params[:post])
    @links = params[:posts][:links_attributes].values.delete_if do |link|
      link["title"] == "" && link["url"] == ""
    end
    @post.links.build(@links)
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end
  
  def show
    @post = Post.find_by_id(params[:id])
    :show
  end
  
  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    redirect_to posts_url
  end
  
  def feed
    @posts = []
    current_user.friend_circle_memberships.each do |membership|
      @posts.concat(membership.friend_circle.posts)
    end
    render :feed
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to user_url(current_user) if logged_in?
    :new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:email], params[:user][:password])

    if @user
      log_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to new_user_url
  end

  def reset_password
    @user = User.find_by_id(params[:id])
    @user.reset_password
  end
  
  def show
    @user = User.find_by_id(params[:id])
    redirect_to user_url(current_user) unless @user == current_user
    :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in_user(user)
    session[:session_token] = user.session_token
  end

  def logged_in?
    !!current_user
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/_form.html.erb
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="friend_circle[user_id]" value= "<%= @user.id %>">
  <input type="hidden" name="friend_circle[friend_ids][]" value="">
  <label for="name">Name</label>
  <input type="text" name="friend_circle[name]" id="name" value="<%= @friend_circle.name %>">
  <br>
  Select Friends To Include In This Circle
  <br>
  <% User.all.each do |user| %>
  <% next if user == @user%>
  <% html_id = "friend_circle_memberships_#{user.id}" %>
  <input type="checkbox" name="friend_circle[friend_ids][]" value="<%=user.id %>" id="<%= html_id %>" <%= "checked" if @friend_circle.friend_ids.include?(user.id)%>>
  <label for="<%= html_id %>"><%= user.email %></label>
  <% end %>
  <br>
  <input type="submit">
</form>

app/views/friend_circles/edit.html.erb
<h1>Edit Your Friend Circle</h1>

<form action="<%= user_friend_circle_url(@user, @friend_circle) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= render "form" %>

app/views/friend_circles/new.html.erb
<h1>Create a New Friends Circle</h1>

<form action="<%= user_friend_circles_url(@user) %>" method="post">
  <%= render "form" %>

app/views/friend_circles/show.html.erb
<h1><%= @friend_circle.name %></h1>

Currently in this Circle:
<ul>
  <% @friend_circle.friend_circle_memberships.each do |member| %>
  <li> <%= member.user.email %></li>
  <% end %>
</ul>

<br>

<%= link_to "Edit Circle", edit_user_friend_circle_url(@friend_circle.user, @friend_circle)%>

<br>
<%= button_to "Delete Circle", user_friend_circle_url(@friend_circle.user, @friend_circle), :method  => :delete %>
<br>

<%= link_to "Back to Profile", user_url(@friend_circle.user)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThingamajig</title>
  <!-- <%= stylesheet_link_tag    "application", :media => "all" %> -->
  <!-- <%= javascript_include_tag "application" %> -->
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash[:errors] ||= []%>
  <ul>
    <% flash[:errors].each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>

<%= yield %>
<br>
<% if logged_in? %>
<br>
Currently Logged In As:
<%= current_user.email %>
<%= button_to('Sign Out', session_url, :method => :delete) %>
<% end %>

</body>
</html>

app/views/posts/feed.html.erb
<h1>Posts Shared With You:</h1>
<ul>
<% @posts.each do |post| %>
<li>Title:
<%= post.title %>
<br>
Body:
<%= post.body %>
<br>
Links:
<ul>
  <% post.links.each do |link| %>
  <li><%= link_to link.title, link.url %></li>
  <% end %>
</ul>
Author:
<%= post.user.email%>
<br>
</li>
<br>
<% end %>
</ul>
<br>

<%= link_to "Back to Profile", user_url(current_user)%>

app/views/posts/index.html.erb
<h1>Posts made by <%= current_user.email %></h1>
<ul>
<% @posts.each do |post| %>
<li><%= link_to post.title, post_url(post) %></li>
<% end %>
</ul>
<br>
<%= link_to "Create a New Post", new_post_url %>
<br>

<%= link_to "Back to Profile", user_url(current_user)%>

app/views/posts/new.html.erb
<h1>Create A Post</h1>


<form action="/posts" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">
  <label for="post_title">Title</label>
  <input type="text" name="post[title]" id="post_title">
  <br>
  <label for="body">Body</label>
  <input type="text" name="post[body]" id="body">
  <br>
  <% @post.links.each do |link| %>
  <label for="link_title<%= link.object_id %>">Link Title</label>
  <input name="posts[links_attributes][<%= link.object_id%>][title]" id="link_title<%= link.object_id %>">
  <label for="link_url<%= link.object_id %>">Link URL</label>
  <input name="posts[links_attributes][<%= link.object_id%>][url]" id="link_url<%= link.object_id %>">
  <br>
  <% end %>
  
  Select Circles to Share This Post With:
  <% current_user.friend_circles.each do |friend_circle| %>
  <% html_id = "friend_circle_#{friend_circle.id}"%>
  <br>
  <input type="checkbox" name="post[shared_circle_ids][]" id="<%= html_id %>" value="<%= friend_circle.id%>">
  <label for="<%= html_id %>"><%= friend_circle.name %></label>
  <br>
  <% end %> 
  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<%= @post.title %>
<br>
<%= @post.body %>
<br>
<ul>
<% @post.links.each do |link| %>
<li><%= link_to link.title, link.url %></li>
<% end %>
</ul>
<br>
This Post is Shared With:
<ul>
<% @post.shared_circles.each do |circle| %>
<li><%= circle.name %></li>
<% end %>
</ul>
<br>
<%= button_to "Delete Post", post_url(@post), :method => :delete %>
<br>
<%= link_to "Back to Profile",user_url(current_user)%>

app/views/users/_form.html.erb
<form action="<%= users_url %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         name="<%= form_authenticity_token %>">

  <label for="email">Email</label>
  <input type="text" id="email" name="user[email]">

  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]">

  <input type="submit" value="Sign Up">
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Profile</h1>

Friend Circles
<ul>
<% @user.friend_circles.each do |friend_circle| %>
<li> <%= link_to "#{friend_circle.name}", user_friend_circle_url(@user, friend_circle) %> </li>
<% end %>
</ul>
<%= link_to "Create New Friend Circle", new_user_friend_circle_url(@user)%>
<br>
<%= link_to "View Posts Shared With Me", feed_url%>
<br>
<%= link_to "View My Posts", posts_url %>

<br>